/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.academia.view.sistema;

import br.com.academia.dao.impl.AdminDAO;
import br.com.academia.dao.impl.AlunoDAO;
import br.com.academia.dao.impl.InstrutorDAO;
import br.com.academia.dao.impl.MatriculaDAO;
import br.com.academia.dao.impl.PagamentoDAO;
import br.com.academia.model.sistema.Academia;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author nikao
 */
public class Relatorio extends javax.swing.JDialog {

    /**
     * Creates new form Relatorio
     */
    public Relatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitlePagamento = new javax.swing.JLabel();
        jlNomeAcademia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlQuantidadeAlunos = new javax.swing.JLabel();
        jlQuantidadeInstrutores = new javax.swing.JLabel();
        jlQuantidadeAdministradores = new javax.swing.JLabel();
        jlFaturamentoMensal = new javax.swing.JLabel();
        jlQuantidadePagamentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jlTitlePagamento.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jlTitlePagamento.setForeground(new java.awt.Color(242, 242, 242));
        jlTitlePagamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitlePagamento.setText("Relatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jlTitlePagamento)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlTitlePagamento)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jlNomeAcademia.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jlNomeAcademia.setText("Academia:  ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jlQuantidadeAlunos.setText("Quantidade de alunos cadastrados: ");

        jlQuantidadeInstrutores.setText("Quantidade de Instrutores cadastrados: ");

        jlQuantidadeAdministradores.setText("Quantidade de Administradores cadastrados: ");

        jlFaturamentoMensal.setText("Faturamento mensal fixo (soma de todas mensalidades): ");

        jlQuantidadePagamentos.setText("Quantidade de pagamentos recebidos: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlQuantidadeInstrutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQuantidadeAdministradores, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jlQuantidadeAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlFaturamentoMensal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQuantidadePagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlQuantidadeAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQuantidadeInstrutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQuantidadeAdministradores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFaturamentoMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQuantidadePagamentos)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNomeAcademia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNomeAcademia)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            int qtdAlunos = new AlunoDAO().quantidade();
            int qtdInstrutores = new InstrutorDAO().quantidade();
            int qtdAdmin = new AdminDAO().quantidade();
            double fatMen = new MatriculaDAO().somaMensalidades();
            int qtdPags = new PagamentoDAO().quantidade();
            
            jlQuantidadeAlunos.setText(jlQuantidadeAlunos.getText() + qtdAlunos);
            jlQuantidadeInstrutores.setText(jlQuantidadeInstrutores.getText() + qtdInstrutores);
            jlQuantidadeAdministradores.setText(jlQuantidadeAdministradores.getText() + qtdAdmin);
            
            jlFaturamentoMensal.setText(jlFaturamentoMensal.getText() + "R$" + fatMen);
            jlQuantidadePagamentos.setText(jlQuantidadePagamentos.getText() + qtdPags);
            jlNomeAcademia.setText(jlNomeAcademia.getText() + academia.getNome());
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel acessar o banco de dados para gerar o relatorio.");
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Relatorio dialog = new Relatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private Academia academia;

    public Academia getAcademia() {
        return academia;
    }

    public void setAcademia(Academia academia) {
        this.academia = academia;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlFaturamentoMensal;
    private javax.swing.JLabel jlNomeAcademia;
    private javax.swing.JLabel jlQuantidadeAdministradores;
    private javax.swing.JLabel jlQuantidadeAlunos;
    private javax.swing.JLabel jlQuantidadeInstrutores;
    private javax.swing.JLabel jlQuantidadePagamentos;
    private javax.swing.JLabel jlTitlePagamento;
    // End of variables declaration//GEN-END:variables
}
