/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.academia.view.fichas;

import br.com.academia.dao.impl.ExercicioDAO;
import br.com.academia.dao.impl.FichaDAO;
import br.com.academia.model.fichas.Ficha;
import br.com.academia.model.pessoas.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikao
 */
public class GerenciarFichas extends javax.swing.JDialog {

    /**
     * Creates new form GerenciarUsuarios
     */
    public GerenciarFichas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitleFichas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbNovaFicha = new javax.swing.JButton();
        jbAlterarFicha = new javax.swing.JButton();
        jbApagarFicha = new javax.swing.JButton();
        jbSairFicha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFicha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jlTitleFichas.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jlTitleFichas.setForeground(new java.awt.Color(242, 242, 242));
        jlTitleFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitleFichas.setText("Fichas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jlTitleFichas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlTitleFichas)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbNovaFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nova_ficha.png"))); // NOI18N
        jbNovaFicha.setText("Novo");
        jbNovaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaFichaActionPerformed(evt);
            }
        });

        jbAlterarFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jbAlterarFicha.setText("Alterar");
        jbAlterarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarFichaActionPerformed(evt);
            }
        });

        jbApagarFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagar.png"))); // NOI18N
        jbApagarFicha.setText("Apagar");
        jbApagarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarFichaActionPerformed(evt);
            }
        });

        jbSairFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jbSairFicha.setText("Fechar");
        jbSairFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairFichaActionPerformed(evt);
            }
        });

        jtFicha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome aluno", "Tipo ficha", "Data criação", "Qtd exercicios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtFicha);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovaFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbApagarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSairFicha)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovaFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbApagarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSairFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            allFichas = new FichaDAO().buscarTodasFichasInstrutor(instrutor.getId());
            
            preencheTable(allFichas);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel acessar o banco de dados para consultar fichas. " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jbNovaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaFichaActionPerformed
        CadastrarFichas cf = new CadastrarFichas(null, true);
        cf.setInstrutor(instrutor);
        cf.setVisible(true);
        
        formWindowOpened(null);
    }//GEN-LAST:event_jbNovaFichaActionPerformed

    private void jbSairFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairFichaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSairFichaActionPerformed

    private void jbAlterarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarFichaActionPerformed
        int row = jtFicha.getSelectedRow();
        
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma ficha para alterar! ");
        } else {
            CadastrarFichas cf = new CadastrarFichas(null, true);
            cf.setInstrutor(instrutor);
            cf.preparedEdit(allFichas.get(row));
            cf.setVisible(true);
        
            formWindowOpened(null);

        }
        

    }//GEN-LAST:event_jbAlterarFichaActionPerformed

    private void jbApagarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarFichaActionPerformed
        int row = jtFicha.getSelectedRow();
        if(jtFicha.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma ficha para apagar! ");
        } else {
            
            if(JOptionPane.showConfirmDialog(null, "Deseja apagar a ficha?",
                    "Apagar Ficha?",
                    JOptionPane.YES_NO_OPTION) 
                    == JOptionPane.YES_OPTION ){
                try {
                    Ficha tmpF = allFichas.get(row);
                    tmpF.setExercicios(new ExercicioDAO().buscarTodosExerciciosFicha(tmpF.getId()));
                    new FichaDAO().apagar(tmpF);
                    JOptionPane.showMessageDialog(null, "Ficha apagada com sucesso.");
                    formWindowOpened(null);
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel apagar a ficha no banco de dados. " + ex.getMessage());
                }
            }
        }
        
    }//GEN-LAST:event_jbApagarFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciarFichas dialog = new GerenciarFichas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private ArrayList<Ficha> allFichas;

    public ArrayList<Ficha> getAllFichas() {
        return allFichas;
    }

    
    
    
    private Usuario instrutor;

    public Usuario getInstrutor() {
        return instrutor;
    }

    public void setInstrutor(Usuario instrutor) {
        this.instrutor = instrutor;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterarFicha;
    private javax.swing.JButton jbApagarFicha;
    private javax.swing.JButton jbNovaFicha;
    private javax.swing.JButton jbSairFicha;
    private javax.swing.JLabel jlTitleFichas;
    private javax.swing.JTable jtFicha;
    // End of variables declaration//GEN-END:variables

    private void preencheTable(ArrayList<Ficha> allFichas){
        DefaultTableModel dtm = (DefaultTableModel) jtFicha.getModel();
        
        while(dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        
        for(Ficha f : allFichas) {
            try {
                int qtdEx = new FichaDAO().quantidadeExerciciosFicha(f.getId());
                String[] linha = { f.getAluno().getNome(), f.getTipoFicha().toString(), f.getDataCriacao().toString(), qtdEx+"" };    
                dtm.addRow(linha);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não foi possivel acessar o banco de dados para retornar a quantidade de exercicios por ficha.");
            } 
        }
        
        
    }
}
