/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.academia.view.users;

import br.com.academia.dao.impl.AlunoDAO;
import br.com.academia.dao.impl.InstrutorDAO;
import br.com.academia.dao.impl.MatriculaDAO;
import br.com.academia.model.pessoas.Aluno;
import br.com.academia.model.pessoas.Instrutor;
import br.com.academia.model.sistema.Academia;
import br.com.academia.model.sistema.Matricula;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nikao
 */
public class InserirAluno extends javax.swing.JDialog {

    /**
     * Creates new form InserirInstrutor
     */
    public InserirAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitleAluno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbSalvarAluno = new javax.swing.JButton();
        jbCancelarAluno = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfValorMensalidadeAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDataVencimentoAluno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jtfNomeAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfLoginAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfSenhaAluno = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jcbInstrutorAluno = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jlTitleAluno.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jlTitleAluno.setForeground(new java.awt.Color(242, 242, 242));
        jlTitleAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitleAluno.setText("Aluno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitleAluno)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlTitleAluno)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbSalvarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        jbSalvarAluno.setText("Salvar");
        jbSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlunoActionPerformed(evt);
            }
        });

        jbCancelarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jbCancelarAluno.setText("Cancelar");
        jbCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalvarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarAluno)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula"));

        jLabel4.setText("Valor mensalidade:");

        jLabel5.setText("Data vencimento pagamento:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do aluno"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Login:");

        jLabel3.setText("Senha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeAluno)
                    .addComponent(jLabel2)
                    .addComponent(jtfLoginAluno)
                    .addComponent(jLabel3)
                    .addComponent(jtfSenhaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLoginAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Preencha no formato do exemplo: 08/03/2022");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfValorMensalidadeAluno))
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfDataVencimentoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorMensalidadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataVencimentoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione um instrutor"));

        jcbInstrutorAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbInstrutorAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbInstrutorAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            allInstrutor = new InstrutorDAO().buscarTodos();
            preencheCombo(allInstrutor);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel buscar os instrutores.\n"+ex.getMessage()); 
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jbSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlunoActionPerformed
        try{    
            Aluno al = new Aluno();
            al.setAcademia(academia);
            al.setLogin(jtfLoginAluno.getText());
            al.setNome(jtfNomeAluno.getText());
            al.setSenha(jtfSenhaAluno.getText());
            al.setInstrutor(allInstrutor.get(jcbInstrutorAluno.getSelectedIndex()));
            
            /*
            Matricula mat = new Matricula();
            Date dataMatricula =new SimpleDateFormat("yyyy-MM-dd").parse(java.time.LocalDate.now().toString());       
           
            String tempDate = jtfDataVencimentoAluno.getText();
            String ano = "",dia = "",mes = "";
            //yyyy-MM-dd
            //dd-MM-yyyy
            if(!tempDate.equals("")){
                ano = tempDate.substring(6,10);
                mes = tempDate.substring(3,5);
                dia = tempDate.substring(0,2);
                tempDate = ano + "-" + mes + "-" + dia; 
            }
            

            Date dataVencMatricula = new SimpleDateFormat("yyyy-MM-dd").parse(tempDate);
            
            mat.setDataMatricula(dataMatricula);
            mat.setDataVencimento(dataVencMatricula);
            mat.setMensalidade(Double.parseDouble(jtfValorMensalidadeAluno.getText()));
            */
            if(jtfNomeAluno.getText().equals("")||
                    jtfLoginAluno.getText().equals("") ||
                    jtfSenhaAluno.getText().equals("") ||
                    jtfValorMensalidadeAluno.getText().equals("") ||
                    jtfDataVencimentoAluno.getText().equals("")
                    ){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de salvar."); 
            } else {
                Matricula mat = new Matricula();
                Date dataMatricula =new SimpleDateFormat("yyyy-MM-dd").parse(java.time.LocalDate.now().toString());       

                String tempDate = jtfDataVencimentoAluno.getText();
                String ano = "",dia = "",mes = "";
                //yyyy-MM-dd
                //dd-MM-yyyy
                if(!tempDate.equals("")){
                    ano = tempDate.substring(6,10);
                    mes = tempDate.substring(3,5);
                    dia = tempDate.substring(0,2);
                    tempDate = ano + "-" + mes + "-" + dia; 
                }


                Date dataVencMatricula = new SimpleDateFormat("yyyy-MM-dd").parse(tempDate);

                mat.setDataMatricula(dataMatricula);
                mat.setDataVencimento(dataVencMatricula);
                mat.setMensalidade(Double.parseDouble(jtfValorMensalidadeAluno.getText()));
                
                
                if(aluno == null){
                    new AlunoDAO().inserir(al);
                    
                    mat.setAluno(new AlunoDAO().buscarPorLoginSenha(al.getLogin(), al.getSenha()));
                    
                    new MatriculaDAO().inserir(mat);
                    
                    JOptionPane.showMessageDialog(null, "O aluno foi cadastrado com sucesso!.");
                } else {
                    al.setId(aluno.getId());
                    new AlunoDAO().alterar(al);
                    Matricula matTemp = new MatriculaDAO().buscarMatriculaAluno(aluno.getId());
                    
                    //Atualizando a matricula com campos novos
                    matTemp.setMensalidade(Double.parseDouble(jtfValorMensalidadeAluno.getText()));
                    matTemp.setDataVencimento(dataVencMatricula);
                   
                    new MatriculaDAO().alterar(matTemp);
                    JOptionPane.showMessageDialog(null, "O aluno foi alterado com sucesso!.");

                    jtfNomeAluno.setText("");
                    jtfLoginAluno.setText("");
                    jtfSenhaAluno.setText("");
                    jtfDataVencimentoAluno.setText("");
                    jtfValorMensalidadeAluno.setText("");
                    this.dispose();
                }


                jtfNomeAluno.setText("");
                jtfLoginAluno.setText("");
                jtfSenhaAluno.setText("");
                jtfDataVencimentoAluno.setText("");
                jtfValorMensalidadeAluno.setText("");
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar o Aluno.\n"+ex.getMessage()); 
        }
    }//GEN-LAST:event_jbSalvarAlunoActionPerformed

    private void jbCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarAlunoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserirAluno dialog = new InserirAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private ArrayList<Instrutor> allInstrutor;
    private Academia academia;
    
    public Academia getAcademia() {
        return academia;
    }

    public void setAcademia(Academia academia) {
        this.academia = academia;
    }

    
    private Aluno aluno;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbCancelarAluno;
    private javax.swing.JButton jbSalvarAluno;
    private javax.swing.JComboBox<String> jcbInstrutorAluno;
    private javax.swing.JLabel jlTitleAluno;
    private javax.swing.JTextField jtfDataVencimentoAluno;
    private javax.swing.JTextField jtfLoginAluno;
    private javax.swing.JTextField jtfNomeAluno;
    private javax.swing.JPasswordField jtfSenhaAluno;
    private javax.swing.JTextField jtfValorMensalidadeAluno;
    // End of variables declaration//GEN-END:variables

    private void preencheCombo(ArrayList<Instrutor> allInstrutor) {
        
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) jcbInstrutorAluno.getModel();
        
        dcb.removeAllElements();
        
        for(Instrutor i : allInstrutor) {
            dcb.addElement(i.getNome());
        }
    }

    void preparedEdit(Aluno al) {
        
        try {
            al.setMatricula(new MatriculaDAO().buscarMatriculaAluno(al.getId()));
            
            aluno = al;
            jtfNomeAluno.setText(al.getNome());
            jtfLoginAluno.setText(al.getLogin());
            jtfSenhaAluno.setText(al.getSenha());
            jtfDataVencimentoAluno.setText("");
            jtfValorMensalidadeAluno.setText(al.getMatricula().getMensalidade()+"");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel acessar o banco de dados." + ex.getMessage());
        }
    }
}
